### ISSUE TITLE
Thunderbird crashes when sending email

### ISSUE THREAD

**Issue by JavierMoncayo** [thundernest/crash-diverter#12]
Every time I try to send an email, the client crashes and only allow me to restart/quit. Crash report attached below.
**Thunderbird**: 91.9.1 (64-bit)
**OS**: 
Distributor ID: Ubuntu
Description: Ubuntu 20.04.4 LTS
Release:	20.04
Codename: focal

**Crash report**:

AdapterDeviceID:0x15d8
AdapterDriverVendor: mesa/radeonsi
AdapterDriverVersion: 21.2.6.0
AdapterVendorID: 0x1002
Add-ons: langpack-es-ES%40thunderbird.mozilla.org:91.0buildid20211020014537,es-es%40dictionaries.addons.mozilla.org:3.2.6,sendlater3%40kamens.us:9.0.10,google%40search.mozilla.org:1.0,bing%40search.mozilla.org:1.0,amazon%40search.mozilla.org:1.1,chambers-en-GB%40search.mozilla.org:1.0,ddg%40search.mozilla.org:1.0,wikipedia%40search.mozilla.org:1.0,thunderbird-compact-dark%40mozilla.org:1.2,langpack-en-GB%40thunderbird.mozilla.org:91.0buildid20220520005021,langpack-en-CA%40thunderbird.mozilla.org:91.0buildid20220520005021
AvailablePageFile: 0
AvailablePhysicalMemory: 20408860672
AvailableSwapMemory: 2147479552
AvailableVirtualMemory: 25303691264
BuildID: 20220520005021
ContentSandboxCapabilities: 119
ContentSandboxCapable: 1
ContentSandboxLevel: 0
CrashTime: 1653913066
DOMIPCEnabled: 1
DesktopEnvironment: gnome
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
InstallTime: 1653326905
IsWayland: 0
Notes: Ubuntu 20.04.4 LTSFP(D00-L1000-W00000000-T000) WR? WR+ OMTP? OMTP- libGL.so.1? libGL.so.1+ GL Context? GL Context+ 
ProductID: {3550f703-e582-4d05-9a08-453d09bdfdc6}
ProductName: Thunderbird
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 1155
StartupCrash: 0
StartupTime: 1653911943
TelemetryEnvironment: {"build":{"applicationId":"{3550f703-e582-4d05-9a08-453d09bdfdc6}","applicationName":"Thunderbird","architecture":"x86-64","buildId":"20220520005021","version":"91.9.1","vendor":null,"displayVersion":"91.9.1","platformVersion":"91.9.1","xpcomAbi":"x86_64-gcc3","updaterAvailable":false},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":30035,"virtualMaxMB":null,"cpu":{"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Linux","version":"5.13.0-44-generic","locale":"en-GB"},"hdd":{"profile":{"model":null,"revision":null,"type":null},"binary":{"model":null,"revision":null,"type":null},"system":{"model":null,"revision":null,"type":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","Headless":false,"EmbeddedInFirefoxReality":null,"adapters":[{"description":"AMD Radeon(TM) Vega 8 Graphics (RAVEN, DRM 3.41.0, 5.13.0-44-generic, LLVM 12.0.0)","vendorID":"0x1002","deviceID":"0x15d8","subsysID":null,"RAM":0,"driver":null,"driverVendor":"mesa/radeonsi","driverVersion":"21.2.6.0","driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":2560,"screenHeight":1440}],"features":{"compositor":"none","hwCompositing":{"status":"available"},"gpuProcess":{"status":"unused"},"wrQualified":{"status":"available"},"webrender":{"status":"available"},"wrCompositor":{"status":"blocklisted:FEATURE_FAILURE_WEBRENDER_COMPOSITOR_DISABLED"},"wrSoftware":{"status":"available"},"openglCompositing":{"status":"available"},"omtp":{"status":"disabled:FEATURE_FAILURE_DISABLED"}}},"appleModelId":null},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":8,"fissionEnabled":false,"telemetryEnabled":false,"locale":"en-GB","intl":{},"update":{"channel":"release","enabled":true,"autoDownload":false,"background":false},"userPrefs":{"browser.cache.disk.capacity":1048576,"browser.search.region":"ES","privacy.donottrackheader.enabled":true,"widget.content.allow-gtk-dark-theme":false,"widget.content.gtk-high-contrast.enabled":true},"sandbox":{"effectiveContentProcessLevel":0,"contentWin32kLockdownState":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":null},"profile":{}}
TelemetrySessionId: 2e6aeaf3-ecbe-4e62-bf2b-5af7846bb6da
ThreadIdNameMapping: 4930:"IPC I/O Parent",4931:"Netlink Monitor",4932:"Socket Thread",4935:"JS Watchdog",4936:"TaskController Thread #0",4937:"TaskController Thread #1",4938:"TaskController Thread #2",4939:"TaskController Thread #3",4940:"TaskController Thread #4",4941:"TaskController Thread #5",4942:"TaskController Thread #6",4943:"TaskController Thread #7",4945:"Timer",4946:"Cache2 I/O",4947:"Cookie",4949:"BackgroundThreadPool #2",4952:"Worker Launcher",4965:"GLXVsyncThread",4978:"Renderer",4979:"WRWorker#0",4980:"WRWorker#1",4983:"WRWorker#4",4984:"WRWorker#5",4981:"WRWorker#2",4982:"WRWorker#3",4985:"WRWorker#6",4986:"WRWorker#7",4988:"WRWorkerLP#1",4987:"WRWorkerLP#0",4989:"WRWorkerLP#2",4990:"WRWorkerLP#3",4991:"WRWorkerLP#4",4992:"WRWorkerLP#5",4993:"WRWorkerLP#6",4994:"WRWorkerLP#7",4995:"Compositor",4996:"ImageIO",4997:"IPDL Background",5000:"Permission",5001:"QuotaManager IO",5005:"HTML5 Parser",5015:"DOM Worker",5019:"StyleThread#3",5016:"StyleThread#0",5017:"StyleThread#1",5018:"StyleThread#2",5020:"StyleThread#4",5021:"StyleThread#5",5023:"ImageBridgeChld",5025:"WRSceneBuilder#1",5026:"WRSceneBuilderLP#1",5027:"WRRenderBackend#1",5055:"TRR Background",5059:"Breakpad Server",5062:"ProcessHangMon",5063:"GMPThread",5085:"mozStorage #1",5175:"WRSceneBuilder#2",5176:"WRSceneBuilderLP#2",5177:"WRRenderBackend#2",5199:"SwComposite",5200:"WRSceneBuilder#4",5201:"WRSceneBuilderLP#4",5202:"WRRenderBackend#4",5203:"SwComposite",5204:"WRSceneBuilder#5",5205:"WRSceneBuilderLP#5",5206:"WRRenderBackend#5",5207:"SwComposite",5208:"WRSceneBuilder#6",5209:"WRSceneBuilderLP#6",5210:"WRRenderBackend#6",5221:"SwComposite",5222:"WRSceneBuilder#8",5223:"WRSceneBuilderLP#8",5224:"WRRenderBackend#8",5228:"mozStorage #4",5233:"URL Classifier",5236:"SwComposite",5237:"WRSceneBuilder#9",5238:"WRSceneBuilderLP#9",5239:"WRRenderBackend#9",5251:"IMAP",5252:"IMAP",5259:"mozStorage #5",5463:"RemoteLzyStream",5493:"DOM Worker",5512:"mozStorage #6",5864:"SwComposite",5865:"WRSceneBuilder#10",5866:"WRSceneBuilderLP#10",5867:"WRRenderBackend#10",5869:"SwComposite",5870:"WRSceneBuilder#11",5871:"WRSceneBuilderLP#11",5872:"WRRenderBackend#11",9350:"mozStorage #7",11475:"WRSceneBuilder#13",11476:"WRSceneBuilderLP#13",11477:"WRRenderBackend#13",11941:"IndexedDB #20",11987:"StreamTrans #18",12035:"StreamTrans #19",12036:"DNS Resolver #4",12037:"DNS Resolver #5",12038:"SSL Cert #5",12043:"DOM Worker",12045:"WRSceneBuilder#14",12046:"WRSceneBuilderLP#14",12047:"WRRenderBackend#14",12048:"SwComposite",12049:"WRSceneBuilder#15",12050:"WRSceneBuilderLP#15",12051:"WRRenderBackend#15",12052:"SwComposite",12053:"WRSceneBuilder#16",12054:"WRSceneBuilderLP#16",12055:"WRRenderBackend#16",12056:"SwComposite",12057:"WRSceneBuilder#17",12058:"WRSceneBuilderLP#17",12059:"WRRenderBackend#17",12060:"SwComposite",12061:"WRSceneBuilder#18",12062:"WRSceneBuilderLP#18",12063:"WRRenderBackend#18",12064:"SwComposite",12065:"WRSceneBuilder#19",12066:"WRSceneBuilderLP#19",12067:"WRRenderBackend#19",12068:"SwComposite",12069:"WRSceneBuilder#20",12070:"WRSceneBuilderLP#20",12071:"WRRenderBackend#20",12072:"SwComposite",12073:"WRSceneBuilder#21",12074:"WRSceneBuilderLP#21",12075:"WRRenderBackend#21",12076:"StreamTrans #20",12077:"mozStorage #8",12107:"WRSceneBuilder#24",12108:"WRSceneBuilderLP#24",12109:"WRRenderBackend#24",
Throttleable: 1
TotalPageFile: 33641271296
TotalPhysicalMemory: 31493791744
URL: about:blank
UptimeTS: 1122.8097772
Version: 91.9.1
useragent_locale: en-GB

This report also contains technical information about the state of the application when it crashed.

**Comment by Sancus** [comment]
This isn't the correct place to file bugs about crashes, this is for the application that deals with crash reports.

Please find your crash report on https://crash-stats.mozilla.org/ and then click on the Bugzilla tab and **click "Thunderbird" next to Create a Bug**.

Note: You can find links to your crash reports in `Help -> More Troubleshooting Information` and then **scroll down until you reach the section entitled `Crash Reports`**.

![image](https://user-images.githubusercontent.com/479671/171077744-381c6564-678f-455d-9885-8cb77d7924b7.png)
